[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manages permission levels and related settings of a group."
edition = "2018"
name = "google_api_rust_client_groupssettings_v1"
version = "0.1.0+20210218"
