[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Views and manages your Google Analytics data."
edition = "2018"
name = "google_api_rust_client_analytics_v3"
version = "0.1.0+20190807"
