[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Help the third party sites to implement federated login."
edition = "2018"
name = "google_api_rust_client_identitytoolkit_v3"
version = "0.1.0+20180723"
