[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Accesses source code repositories hosted by Google."
edition = "2018"
name = "google_api_rust_client_sourcerepo_v1"
version = "0.2.1+20210125"
