[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Cloud Life Sciences is a suite of services and tools for managing, processing, and transforming life sciences data."
edition = "2018"
name = "google_api_rust_client_lifesciences_v2beta"
version = "0.1.0+20210213"
