[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "API for Verified Access chrome extension to provide credential verification for chrome devices connecting to an enterprise network"
edition = "2018"
name = "google_api_rust_client_verifiedaccess_v1"
version = "0.1.0+20200828"
