[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Builds and manages container-based applications, powered by the open source Kubernetes technology."
edition = "2018"
name = "google_api_rust_client_container_v1"
version = "0.1.0+20210216"
