[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Provides polling places, early vote locations, contest data, election officials, and government representatives for U.S. residential addresses."
edition = "2018"
name = "google_api_rust_client_civicinfo_v2"
version = "0.2.1+20210108"
