[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Stores sensitive data such as API keys, passwords, and certificates. Provides convenience while improving security. "
edition = "2018"
name = "google_api_rust_client_secretmanager_v1"
version = "0.2.1+20210205"
