[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "The Google Tasks API lets you manage your tasks and task lists."
edition = "2018"
name = "google_api_rust_client_tasks_v1"
version = "0.1.0+20210220"
