[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "The cloud asset API manages the history and inventory of cloud resources."
edition = "2018"
name = "google_api_rust_client_cloudasset_v1"
version = "0.1.0+20210212"
