[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manages lightweight user-provided functions executed in response to events."
edition = "2018"
name = "google_api_rust_client_cloudfunctions_v1"
version = "0.1.0+20210211"
