[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Controls access to cloud applications running on Google Cloud Platform."
edition = "2018"
name = "google_api_rust_client_iap_v1beta1"
version = "0.1.0+20210212"
