[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Provides information about other Google APIs, such as what APIs are available, the resource, and method details for each API."
edition = "2018"
name = "google_api_rust_client_discovery_v1"
version = "0.1.0+20200806"
