[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Programmatically creates and manages Firebase Dynamic Links."
edition = "2018"
name = "google_api_rust_client_firebasedynamiclinks_v1"
version = "0.2.1+20210222"
