[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manage your product listings and accounts for Google Shopping"
edition = "2018"
name = "google_api_rust_client_content_v2"
version = "0.1.0+20210222"
