[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "AI Platform Notebooks API is used to manage notebook resources in Google Cloud."
edition = "2018"
name = "google_api_rust_client_notebooks_v1"
version = "0.1.0+20210122"
