[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Creates and runs virtual machines on Google Cloud Platform."
edition = "2018"
name = "google_api_rust_client_compute_alpha"
version = "0.1.0+20210209"
