[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manages keys and performs cryptographic operations in a central cloud service, for direct use by other cloud resources and applications. "
edition = "2018"
name = "google_api_rust_client_cloudkms_v1"
version = "0.1.0+20210210"
