[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "The Firebase Management API enables programmatic setup and management of Firebase projects, including a project's Firebase resources and Firebase apps."
edition = "2018"
name = "google_api_rust_client_firebase_v1beta1"
version = "0.2.1+20210223"
