[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Creates and manages jobs run on a regular recurring schedule."
edition = "2018"
name = "google_api_rust_client_cloudscheduler_v1beta1"
version = "0.1.0+20210209"
