[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions."
edition = "2018"
name = "google_api_rust_client_drive_v3"
version = "0.2.1+20210214"
