[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Deploy and manage user provided container images that scale automatically based on HTTP traffic."
edition = "2018"
name = "google_api_rust_client_run_v1"
version = "0.1.0+20210212"
