[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Provides admission control and telemetry reporting for services integrated with Service Infrastructure. "
edition = "2018"
name = "google_api_rust_client_servicecontrol_v1"
version = "0.1.0+20210212"
