[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "The Cloud Filestore API is used for creating and managing cloud file servers."
edition = "2018"
name = "google_api_rust_client_file_v1"
version = "0.2.1+20210211"
