[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "This API allows clients to access and modify container and tag configuration."
edition = "2018"
name = "google_api_rust_client_tagmanager_v1"
version = "0.1.0+20210222"
