[package]
name = "google-api-rust-client-gen"
version = "0.2.1"
authors = ["Ezra Celli <ezra@ezracelli.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
change-case = "0.2.0"
derive_builder = "0.9.0"
dialoguer = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
proc-macro2 = "1.0.24"
quote = "1.0.9"
regex = "1.4.3"
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
serde_with = "1.6.4"
structopt = "0.3.21"
tokio = { version = "1.2.0", features = ["fs", "macros", "process", "rt-multi-thread"] }
toml = "0.5.8"
