[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Manages Hadoop-based clusters and jobs on Google Cloud Platform."
edition = "2018"
name = "google_api_rust_client_dataproc_v1beta2"
version = "0.2.2+20210218"
