[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360."
edition = "2018"
name = "google_api_rust_client_dfareporting_v3_3"
version = "0.1.0+20210210"
