[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Access custom machine learning models hosted via Firebase ML."
edition = "2018"
name = "google_api_rust_client_firebaseml_v1beta2"
version = "0.1.0+20210222"
