[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Creates, reads, and updates metadata for Google Cloud Platform resource containers."
edition = "2018"
name = "google_api_rust_client_cloudresourcemanager_v1"
version = "0.1.0+20210222"
