[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Stores and retrieves potentially large, immutable data objects."
edition = "2018"
name = "google_api_rust_client_storage_v1"
version = "0.1.0+20210219"
