[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "The Search Ads 360 API allows developers to automate uploading conversions and downloading reports from Search Ads 360."
edition = "2018"
name = "google_api_rust_client_doubleclicksearch_v2"
version = "0.1.0+20210217"
