#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Empty response."]
pub struct EmptyResponse {
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Apiary error details"]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Describes one specific error."]
pub struct ErrorProto {
    #[serde(rename = "argument")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Error arguments, to be used when building user-friendly error messages given the error domain and code. Different error codes require different arguments."]
    pub argument: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    #[serde(rename = "code")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Error code in the error domain. This should correspond to a value of the enum type whose name is in domain. See the core error domain in error_domain.proto."]
    pub code: ::std::option::Option<::std::string::String>,
    #[serde(rename = "debugInfo")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Debugging information, which should not be shared externally."]
    pub debug_info: ::std::option::Option<::std::string::String>,
    #[serde(rename = "domain")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Error domain. RoSy services can define their own domain and error codes. This should normally be the name of an enum type, such as: gdata.CoreErrorDomain"]
    pub domain: ::std::option::Option<::std::string::String>,
    #[serde(rename = "externalErrorMessage")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "A short explanation for the error, which can be shared outside Google. Please set domain, code and arguments whenever possible instead of this error message so that external APIs can build safe error messages themselves. External messages built in a RoSy interface will most likely refer to information and concepts that are not available externally and should not be exposed. It is safer if external APIs can understand the errors and decide what the error message should look like."]
    pub external_error_message: ::std::option::Option<::std::string::String>,
    #[serde(rename = "location")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Location of the error, as specified by the location type. If location_type is PATH, this should be a path to a field that's relative to the request, using FieldPath notation (net/proto2/util/public/field_path.h). Examples: authenticated_user.gaia_id resource.address[2].country"]
    pub location: ::std::option::Option<::std::string::String>,
    #[serde(rename = "locationType")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub location_type: ::std::option::Option<ErrorProtoLocationTypeEnum>,
}
#[derive(Debug, PartialEq, Copy, Clone, serde :: Serialize, serde :: Deserialize)]
pub enum ErrorProtoLocationTypeEnum {
    #[serde(rename = "PATH")]
    #[doc = "location is an xpath-like path pointing to the request field that caused the error."]
    Path,
    #[serde(rename = "OTHER")]
    #[doc = "other location type which can safely be shared externally."]
    Other,
    #[serde(rename = "PARAMETER")]
    #[doc = "Location is request paramater. This maps to the {@link PARAMETERS} in {@link MessageLocation}."]
    Parameter,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Request Error information. The presence of an error field signals that the operation has failed."]
pub struct Errors {
    #[serde(rename = "code")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead."]
    pub code: ::std::option::Option<ErrorsCodeEnum>,
    #[serde(rename = "error")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Specific error description and codes"]
    pub error: ::std::option::Option<::std::vec::Vec<::std::boxed::Box<ErrorProto>>>,
    #[serde(rename = "requestId")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Request identifier generated by the service, which can be used to identify the error in the logs"]
    pub request_id: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, PartialEq, Copy, Clone, serde :: Serialize, serde :: Deserialize)]
#[doc = "Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead."]
pub enum ErrorsCodeEnum {
    #[serde(rename = "BAD_REQUEST")]
    #[doc = ""]
    BadRequest,
    #[serde(rename = "FORBIDDEN")]
    #[doc = ""]
    Forbidden,
    #[serde(rename = "NOT_FOUND")]
    #[doc = ""]
    NotFound,
    #[serde(rename = "CONFLICT")]
    #[doc = ""]
    Conflict,
    #[serde(rename = "GONE")]
    #[doc = ""]
    Gone,
    #[serde(rename = "PRECONDITION_FAILED")]
    #[doc = ""]
    PreconditionFailed,
    #[serde(rename = "INTERNAL_ERROR")]
    #[doc = ""]
    InternalError,
    #[serde(rename = "SERVICE_UNAVAILABLE")]
    #[doc = ""]
    ServiceUnavailable,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "A group."]
pub struct Group {
    #[serde(rename = "contentDetails")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The `contentDetails` object contains additional information about the group, such as the number and type of items that it contains."]
    pub content_details: ::std::option::Option<::std::boxed::Box<GroupContentDetails>>,
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Apiary error details"]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
    #[serde(rename = "etag")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The Etag of this resource."]
    pub etag: ::std::option::Option<::std::string::String>,
    #[serde(rename = "id")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The ID that YouTube uses to uniquely identify the group."]
    pub id: ::std::option::Option<::std::string::String>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Identifies the API resource's type. The value will be `youtube#group`."]
    pub kind: ::std::option::Option<::std::string::String>,
    #[serde(rename = "snippet")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The `snippet` object contains basic information about the group, including its creation date and name."]
    pub snippet: ::std::option::Option<::std::boxed::Box<GroupSnippet>>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "A group's content details."]
pub struct GroupContentDetails {
    #[serde(rename = "itemCount")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The number of items in the group."]
    pub item_count: ::std::option::Option<::std::string::String>,
    #[serde(rename = "itemType")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The type of resources that the group contains. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`"]
    pub item_type: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "A group item."]
pub struct GroupItem {
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Apiary error details"]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
    #[serde(rename = "etag")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The Etag of this resource."]
    pub etag: ::std::option::Option<::std::string::String>,
    #[serde(rename = "groupId")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The ID that YouTube uses to uniquely identify the group that contains the item."]
    pub group_id: ::std::option::Option<::std::string::String>,
    #[serde(rename = "id")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is included in the group. Note that this ID refers specifically to the inclusion of that resource in a particular group and is different than the channel ID, video ID, playlist ID, or asset ID that uniquely identifies the resource itself. The `resource.id` property's value specifies the unique channel, video, playlist, or asset ID."]
    pub id: ::std::option::Option<::std::string::String>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Identifies the API resource's type. The value will be `youtube#groupItem`."]
    pub kind: ::std::option::Option<::std::string::String>,
    #[serde(rename = "resource")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The `resource` object contains information that identifies the item being added to the group."]
    pub resource: ::std::option::Option<::std::boxed::Box<GroupItemResource>>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GroupItemResource {
    #[serde(rename = "id")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The channel, video, playlist, or asset ID that YouTube uses to uniquely identify the item that is being added to the group."]
    pub id: ::std::option::Option<::std::string::String>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Identifies the type of resource being added to the group. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`"]
    pub kind: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "A group snippet."]
pub struct GroupSnippet {
    #[serde(rename = "publishedAt")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The date and time that the group was created. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format."]
    pub published_at: ::std::option::Option<::std::string::String>,
    #[serde(rename = "title")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The group name. The value must be a non-empty string."]
    pub title: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Response message for GroupsService.ListGroupItems."]
pub struct ListGroupItemsResponse {
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Apiary error details"]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
    #[serde(rename = "etag")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The Etag of this resource."]
    pub etag: ::std::option::Option<::std::string::String>,
    #[serde(rename = "items")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "A list of groups that match the API request parameters. Each item in the list represents a `groupItem` resource."]
    pub items: ::std::option::Option<::std::vec::Vec<::std::boxed::Box<GroupItem>>>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Identifies the API resource's type. The value will be `youtube#groupItemListResponse`."]
    pub kind: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Response message for GroupsService.ListGroups."]
pub struct ListGroupsResponse {
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Apiary error details"]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
    #[serde(rename = "etag")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The Etag of this resource."]
    pub etag: ::std::option::Option<::std::string::String>,
    #[serde(rename = "items")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "A list of groups that match the API request parameters. Each item in the list represents a `group` resource."]
    pub items: ::std::option::Option<::std::vec::Vec<::std::boxed::Box<Group>>>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "Identifies the API resource's type. The value will be `youtube#groupListResponse`."]
    pub kind: ::std::option::Option<::std::string::String>,
    #[serde(rename = "nextPageToken")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The token that can be used as the value of the `pageToken` parameter to retrieve the next page in the result set."]
    pub next_page_token: ::std::option::Option<::std::string::String>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "Response message for TargetedQueriesService.Query."]
pub struct QueryResponse {
    #[serde(rename = "columnHeaders")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "This value specifies information about the data returned in the `rows` fields. Each item in the `columnHeaders` list identifies a field returned in the `rows` value, which contains a list of comma-delimited data. The `columnHeaders` list will begin with the dimensions specified in the API request, which will be followed by the metrics specified in the API request. The order of both dimensions and metrics will match the ordering in the API request. For example, if the API request contains the parameters `dimensions=ageGroup,gender&metrics=viewerPercentage`, the API response will return columns in this order: `ageGroup`, `gender`, `viewerPercentage`."]
    pub column_headers:
        ::std::option::Option<::std::vec::Vec<::std::boxed::Box<ResultTableColumnHeader>>>,
    #[serde(rename = "errors")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "When set, indicates that the operation failed."]
    pub errors: ::std::option::Option<::std::boxed::Box<Errors>>,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "This value specifies the type of data included in the API response. For the query method, the kind property value will be `youtubeAnalytics#resultTable`."]
    pub kind: ::std::option::Option<::std::string::String>,
    #[serde(rename = "rows")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The list contains all rows of the result table. Each item in the list is an array that contains comma-delimited data corresponding to a single row of data. The order of the comma-delimited data fields will match the order of the columns listed in the `columnHeaders` field. If no data is available for the given query, the `rows` element will be omitted from the response. The response for a query with the `day` dimension will not contain rows for the most recent days."]
    pub rows: ::std::option::Option<::std::vec::Vec<::std::vec::Vec<::serde_json::Value>>>,
}
#[derive(Debug, Default, PartialEq, Clone, serde :: Serialize, serde :: Deserialize)]
#[serde(deny_unknown_fields)]
#[doc = "The description of a column of the result table."]
pub struct ResultTableColumnHeader {
    #[serde(rename = "columnType")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The type of the column (`DIMENSION` or `METRIC`)."]
    pub column_type: ::std::option::Option<::std::string::String>,
    #[serde(rename = "dataType")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The type of the data in the column (`STRING`, `INTEGER`, `FLOAT`, etc.)."]
    pub data_type: ::std::option::Option<::std::string::String>,
    #[serde(rename = "name")]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    #[doc = "The name of the dimension or metric."]
    pub name: ::std::option::Option<::std::string::String>,
}
