[dependencies]
derive_builder = "0.9"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "OS management tools that can be used for patch management, patch compliance, and configuration management on VM instances."
edition = "2018"
name = "google_api_rust_client_osconfig_v1beta"
version = "0.2.2+20210122"
