[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Service Directory is a platform for discovering, publishing, and connecting services. "
edition = "2018"
name = "google_api_rust_client_servicedirectory_v1beta1"
version = "0.1.0+20210211"
