[dependencies]
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[package]
authors = ["Ezra Celli <ezra@ezracelli.com>"]
description = "Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP."
edition = "2018"
name = "google_api_rust_client_memcache_v1"
version = "0.1.0+20210209"
